version: "3.7"

services:
  app:
    container_name: "u8views_shortener_go_app"
    image: golang:1.21.0-alpine
    working_dir: /go/src/github.com/u8views/go-url-shortener
    volumes:
      - .:/go/src/github.com/u8views/go-url-shortener
      - ./.docker/volumes/go/tls-certificates:/var/lib/tls-certificates/data/
    ports:
      - "80:80"
      - "443:443"
    command: "sleep infinity"
